server:
  port: 9090 # api gateway 서버의 port 9090으로 설정

spring:
  cloud:
    gateway:
      httpclient: # global timeout 설정
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: path_simple_hello
          uri: http://localhost:8080
          predicates:
            - Path=/hello
          metadata: # route 별 타임아웃 설정
            response-timeout: 200
            connect-timeout: 200
        - id: rewrite_route
          uri: http://localhost:8080
          predicates:
            - Path=/hello
          filters:
            - RewritePath=/gateway-hello, /microservice-hello
        - id: add-header-route
          uri: http://httpbin.org
          predicates:
            - Path=/get
          filters:
            - AddRequestHeader=role, hello-api
